export interface Job {
  id: string
  title: string
  description: string
  budget: number
  timeline: string
  category: string
  skills: string[]
  clientId: string
  clientName: string
  createdAt: string
  status: "open" | "in-progress" | "completed"
  applications: number
  location: string
  workType: "Remote" | "Onsite" | "Hybrid" | "Online"
}

export const defaultJobs: Job[] = [
  // Web Development Jobs
  {
    id: "job-1",
    title: "Frontend React Developer",
    description:
      "We are looking for an experienced React developer to build a modern, responsive web application. The project involves creating reusable components, implementing state management with Redux, and ensuring cross-browser compatibility. Experience with TypeScript and modern CSS frameworks is preferred.",
    budget: 50000,
    timeline: "1 month",
    category: "web-development",
    skills: ["React", "JavaScript", "TypeScript", "CSS", "HTML"],
    clientId: "client-1",
    clientName: "TechNova Solutions",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 12,
    location: "Bangalore",
    workType: "Remote",
  },
  {
    id: "job-2",
    title: "Full Stack Developer (MERN)",
    description:
      "Join our team to develop a comprehensive e-commerce platform using the MERN stack. Responsibilities include building RESTful APIs, implementing authentication, database design, and creating an intuitive user interface. Strong knowledge of MongoDB, Express.js, React, and Node.js required.",
    budget: 75000,
    timeline: "2 months",
    category: "web-development",
    skills: ["MongoDB", "Express.js", "React", "Node.js", "JavaScript"],
    clientId: "client-2",
    clientName: "CodeHive Pvt Ltd",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 8,
    location: "Chennai",
    workType: "Onsite",
  },
  {
    id: "job-3",
    title: "WordPress Website Designer",
    description:
      "Create a professional WordPress website for a digital marketing agency. The project includes custom theme development, plugin integration, SEO optimization, and responsive design. Experience with PHP, MySQL, and WordPress best practices is essential.",
    budget: 30000,
    timeline: "3 weeks",
    category: "web-development",
    skills: ["WordPress", "PHP", "MySQL", "CSS", "HTML"],
    clientId: "client-3",
    clientName: "DigitalWaves",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 15,
    location: "Remote",
    workType: "Remote",
  },
  {
    id: "job-4",
    title: "E-commerce Web Developer",
    description:
      "Develop a modern e-commerce website with advanced features including product catalog, shopping cart, payment integration, and admin dashboard. The project requires expertise in modern web technologies and e-commerce best practices.",
    budget: 65000,
    timeline: "1.5 months",
    category: "web-development",
    skills: ["JavaScript", "React", "Node.js", "Payment Integration", "Database"],
    clientId: "client-4",
    clientName: "ShopSphere",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 6,
    location: "Hyderabad",
    workType: "Hybrid",
  },
  {
    id: "job-5",
    title: "Backend API Developer (Node.js)",
    description:
      "Build robust and scalable RESTful APIs using Node.js and Express.js. The project involves database design, authentication implementation, API documentation, and performance optimization. Experience with cloud services and microservices architecture is a plus.",
    budget: 80000,
    timeline: "2 months",
    category: "web-development",
    skills: ["Node.js", "Express.js", "MongoDB", "API Development", "Authentication"],
    clientId: "client-5",
    clientName: "DataLink Systems",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 9,
    location: "Pune",
    workType: "Remote",
  },

  // Mobile Development Jobs
  {
    id: "job-6",
    title: "Android App Developer (Kotlin)",
    description:
      "Develop a native Android application using Kotlin with modern Android development practices. The app should include user authentication, real-time data synchronization, push notifications, and material design implementation.",
    budget: 60000,
    timeline: "1 month",
    category: "mobile-development",
    skills: ["Kotlin", "Android", "Firebase", "Material Design", "API Integration"],
    clientId: "client-6",
    clientName: "AppifyTech",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 11,
    location: "Mumbai",
    workType: "Remote",
  },
  {
    id: "job-7",
    title: "iOS Swift Developer",
    description:
      "Create a sophisticated iOS application using Swift and SwiftUI. The project includes complex UI animations, Core Data integration, push notifications, and App Store optimization. Experience with iOS design guidelines and performance optimization required.",
    budget: 90000,
    timeline: "2 months",
    category: "mobile-development",
    skills: ["Swift", "SwiftUI", "iOS", "Core Data", "App Store"],
    clientId: "client-7",
    clientName: "BrightApps",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 5,
    location: "Delhi",
    workType: "Onsite",
  },
  {
    id: "job-8",
    title: "React Native Developer",
    description:
      "Build a cross-platform mobile application using React Native. The app should work seamlessly on both iOS and Android platforms with native performance and user experience. Integration with third-party services and APIs required.",
    budget: 70000,
    timeline: "1.5 months",
    category: "mobile-development",
    skills: ["React Native", "JavaScript", "iOS", "Android", "API Integration"],
    clientId: "client-8",
    clientName: "MobileFirst Co.",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 13,
    location: "Remote",
    workType: "Remote",
  },
  {
    id: "job-9",
    title: "Flutter Developer",
    description:
      "Develop a beautiful and performant mobile application using Flutter framework. The project involves creating custom widgets, state management implementation, and integration with backend services. Experience with Dart programming language essential.",
    budget: 55000,
    timeline: "1 month",
    category: "mobile-development",
    skills: ["Flutter", "Dart", "Mobile Development", "State Management", "API Integration"],
    clientId: "client-9",
    clientName: "PixelApps",
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 7,
    location: "Bangalore",
    workType: "Hybrid",
  },
  {
    id: "job-10",
    title: "Mobile UI/UX Prototyping",
    description:
      "Create interactive prototypes and wireframes for a mobile application. The project includes user research, information architecture, visual design, and usability testing. Proficiency in design tools like Figma, Sketch, or Adobe XD required.",
    budget: 40000,
    timeline: "3 weeks",
    category: "design",
    skills: ["UI/UX Design", "Figma", "Prototyping", "User Research", "Mobile Design"],
    clientId: "client-10",
    clientName: "AppSphere Labs",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 18,
    location: "Chennai",
    workType: "Remote",
  },

  // Design Jobs
  {
    id: "job-11",
    title: "UI/UX Designer",
    description:
      "Design a comprehensive user interface and experience for a SaaS platform. The project involves user journey mapping, wireframing, visual design, and design system creation. Strong understanding of design principles and user-centered design approach required.",
    budget: 35000,
    timeline: "1 month",
    category: "design",
    skills: ["UI/UX Design", "Figma", "User Research", "Design Systems", "Prototyping"],
    clientId: "client-11",
    clientName: "Creatify Studios",
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 22,
    location: "Remote",
    workType: "Remote",
  },
  {
    id: "job-12",
    title: "Logo & Branding Designer",
    description:
      "Create a complete brand identity including logo design, color palette, typography, and brand guidelines. The project requires creativity, attention to detail, and understanding of brand positioning. Portfolio showcasing previous branding work essential.",
    budget: 25000,
    timeline: "2 weeks",
    category: "design",
    skills: ["Logo Design", "Branding", "Adobe Illustrator", "Brand Identity", "Creative Design"],
    clientId: "client-12",
    clientName: "BrandCraft",
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 25,
    location: "Pune",
    workType: "Online",
  },
  {
    id: "job-13",
    title: "Product Design Specialist",
    description:
      "Lead the design process for a complex B2B software product. Responsibilities include user research, interaction design, visual design, and collaboration with development teams. Experience with enterprise software design and design thinking methodologies preferred.",
    budget: 70000,
    timeline: "2 months",
    category: "design",
    skills: ["Product Design", "User Research", "Interaction Design", "Design Thinking", "B2B Software"],
    clientId: "client-13",
    clientName: "InnoTech",
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 8,
    location: "Bangalore",
    workType: "Onsite",
  },
  {
    id: "job-14",
    title: "Graphic Designer (Social Media)",
    description:
      "Create engaging visual content for social media platforms including Instagram, Facebook, LinkedIn, and Twitter. The project involves designing posts, stories, banners, and promotional materials. Knowledge of social media trends and platform specifications required.",
    budget: 30000,
    timeline: "3 weeks",
    category: "design",
    skills: ["Graphic Design", "Social Media", "Adobe Creative Suite", "Visual Content", "Brand Consistency"],
    clientId: "client-14",
    clientName: "ViralVision",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 19,
    location: "Remote",
    workType: "Remote",
  },
  {
    id: "job-15",
    title: "Web App Design (Figma)",
    description:
      "Design a modern web application interface using Figma with focus on user experience and visual appeal. The project includes creating responsive designs, component libraries, and interactive prototypes. Strong skills in modern design trends and tools required.",
    budget: 45000,
    timeline: "1 month",
    category: "design",
    skills: ["Figma", "Web Design", "UI/UX", "Responsive Design", "Component Libraries"],
    clientId: "client-15",
    clientName: "UXHive",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 14,
    location: "Hyderabad",
    workType: "Online",
  },

  // Writing Jobs
  {
    id: "job-16",
    title: "Content Writer (Tech Blogs)",
    description:
      "Write high-quality technical blog posts covering topics like web development, AI, cloud computing, and emerging technologies. The content should be informative, engaging, and SEO-optimized. Strong research skills and technical writing experience required.",
    budget: 20000,
    timeline: "2 weeks",
    category: "writing",
    skills: ["Technical Writing", "Content Creation", "SEO", "Research", "Blog Writing"],
    clientId: "client-16",
    clientName: "WriteUpHub",
    createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 28,
    location: "Remote",
    workType: "Remote",
  },
  {
    id: "job-17",
    title: "Copywriter (Ad Campaigns)",
    description:
      "Create compelling copy for digital advertising campaigns across multiple platforms. The project involves writing ad copy, email campaigns, landing page content, and social media posts. Experience with conversion optimization and A/B testing preferred.",
    budget: 40000,
    timeline: "1 month",
    category: "writing",
    skills: ["Copywriting", "Digital Marketing", "Ad Copy", "Email Marketing", "Conversion Optimization"],
    clientId: "client-17",
    clientName: "MarketMasters",
    createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 16,
    location: "Delhi",
    workType: "Online",
  },
  {
    id: "job-18",
    title: "Research Writer (Academic)",
    description:
      "Conduct thorough research and write academic papers on various topics in computer science and technology. The project requires strong analytical skills, proper citation methods, and adherence to academic writing standards.",
    budget: 30000,
    timeline: "1 month",
    category: "writing",
    skills: ["Academic Writing", "Research", "Data Analysis", "Citation", "Technical Documentation"],
    clientId: "client-18",
    clientName: "ScholarWorks",
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 12,
    location: "Chennai",
    workType: "Remote",
  },

  // Marketing Jobs
  {
    id: "job-19",
    title: "Digital Marketing Associate",
    description:
      "Manage comprehensive digital marketing campaigns including SEO, SEM, social media marketing, and content marketing. The role involves campaign optimization, performance analysis, and ROI improvement. Experience with marketing tools and analytics platforms required.",
    budget: 45000,
    timeline: "1 month",
    category: "marketing",
    skills: ["Digital Marketing", "SEO", "SEM", "Social Media", "Analytics"],
    clientId: "client-19",
    clientName: "Growthify",
    createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 21,
    location: "Hyderabad",
    workType: "Remote",
  },
  {
    id: "job-20",
    title: "Social Media Manager",
    description:
      "Develop and execute social media strategies across multiple platforms to increase brand awareness and engagement. Responsibilities include content creation, community management, influencer partnerships, and performance tracking.",
    budget: 50000,
    timeline: "1.5 months",
    category: "marketing",
    skills: ["Social Media Marketing", "Content Strategy", "Community Management", "Influencer Marketing", "Analytics"],
    clientId: "client-20",
    clientName: "ViralBuzz",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 17,
    location: "Delhi",
    workType: "Online",
  },

  // Data Science Jobs
  {
    id: "job-21",
    title: "Data Analyst (SQL & Excel)",
    description:
      "Analyze large datasets to extract meaningful insights and create comprehensive reports. The project involves data cleaning, statistical analysis, visualization, and presentation of findings. Proficiency in SQL, Excel, and data visualization tools required.",
    budget: 65000,
    timeline: "1.5 months",
    category: "data-science",
    skills: ["SQL", "Excel", "Data Analysis", "Statistics", "Data Visualization"],
    clientId: "client-21",
    clientName: "InsightTech",
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 10,
    location: "Remote",
    workType: "Remote",
  },
  {
    id: "job-22",
    title: "Machine Learning Engineer",
    description:
      "Develop and deploy machine learning models for predictive analytics and automation. The project involves data preprocessing, model training, evaluation, and production deployment. Strong background in Python, scikit-learn, and cloud platforms required.",
    budget: 90000,
    timeline: "2 months",
    category: "data-science",
    skills: ["Machine Learning", "Python", "TensorFlow", "Data Science", "Cloud Computing"],
    clientId: "client-22",
    clientName: "AIWorks",
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 6,
    location: "Bangalore",
    workType: "Onsite",
  },
  {
    id: "job-23",
    title: "Data Visualization Expert (Tableau/PowerBI)",
    description:
      "Create interactive dashboards and visualizations using Tableau and PowerBI to help stakeholders make data-driven decisions. The project involves connecting to various data sources, designing intuitive visualizations, and providing training to end users.",
    budget: 70000,
    timeline: "1 month",
    category: "data-science",
    skills: ["Tableau", "PowerBI", "Data Visualization", "Dashboard Design", "Business Intelligence"],
    clientId: "client-23",
    clientName: "VizHub",
    createdAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
    status: "open",
    applications: 8,
    location: "Chennai",
    workType: "Remote",
  },
]
